import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/index',
        'getting-started/installation',
        'getting-started/first-deployment',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/components',
        'architecture/gitops',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'concepts/projects',
        'concepts/workloads',
        'concepts/addons',
        'concepts/builds',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/cluster-registration',
        'guides/deploying-applications',
        'guides/managing-addons',
        'guides/monitoring',
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
